const fs = require("fs");
const path = require("path");
const vm = require("vm");

const root = path.resolve(__dirname, "..");
const reports = [
  path.join(root, "docs", "duplicate_report.md"),
  path.join(root, "docs", "similar_report.md")
];
const bankFiles = [
  "data/question_bank.js",
  "data/supplemental_questions.js",
  "data/full_coverage_questions.js",
  "data/final_bank_questions.js",
  "data/answer_overrides.js"
];

const mergeText = "\u5408\u5e76";
const keepText = "\u5168\u90e8\u4fdd\u7559";
const partialText = "\u90e8\u5206\u5408\u5e76";

function loadQuestions() {
  const sandbox = { window: {}, console };
  sandbox.window.window = sandbox.window;
  for (const file of bankFiles) {
    const code = fs.readFileSync(path.join(root, file), "utf8");
    vm.runInNewContext(code, sandbox, { filename: file });
  }
  return sandbox.window.QUESTION_BANK || [];
}

function parseReport(file) {
  const text = fs.readFileSync(file, "utf8");
  return text
    .split(/\n(?=##\s+[^\n]*组\s+\d+)/)
    .filter((chunk) => /##\s+[^\n]*组\s+\d+/.test(chunk))
    .map((chunk) => {
      const title = (chunk.match(/##\s+([^\n]+)/) || [])[1] || "";
      const ids = [...chunk.matchAll(/###\s+\d+\.\s+([a-z0-9-]+)/gi)].map((match) => match[1]);
      const checked = [...chunk.matchAll(/- \[x\].*/g)].map((match) => match[0]);
      const joined = checked.join(" | ");
      let decision = "other";
      if (!checked.length) decision = "unchecked";
      else if (joined.includes(partialText)) decision = "partial";
      else if (joined.includes(keepText)) decision = "keep";
      else if (joined.includes(mergeText)) decision = "merge";
      return { file: path.relative(root, file).replace(/\\/g, "/"), title, ids, decision };
    });
}

class DisjointSet {
  constructor() {
    this.parent = new Map();
  }

  add(value) {
    if (!this.parent.has(value)) this.parent.set(value, value);
  }

  find(value) {
    this.add(value);
    const parent = this.parent.get(value);
    if (parent === value) return value;
    const rootValue = this.find(parent);
    this.parent.set(value, rootValue);
    return rootValue;
  }

  union(left, right) {
    const leftRoot = this.find(left);
    const rightRoot = this.find(right);
    if (leftRoot !== rightRoot) this.parent.set(rightRoot, leftRoot);
  }
}

function main() {
  const questions = loadQuestions();
  const order = new Map(questions.map((question, index) => [question.id, index]));
  const groups = reports.flatMap(parseReport);
  const dsu = new DisjointSet();

  const missing = new Set();
  for (const group of groups) {
    for (const id of group.ids) {
      if (!order.has(id)) missing.add(id);
    }
    if (group.decision !== "merge") continue;
    const ids = group.ids.filter((id) => order.has(id));
    if (ids.length < 2) continue;
    ids.forEach((id) => dsu.add(id));
    for (let index = 1; index < ids.length; index += 1) {
      dsu.union(ids[0], ids[index]);
    }
  }

  const componentMap = new Map();
  for (const id of dsu.parent.keys()) {
    const rootId = dsu.find(id);
    if (!componentMap.has(rootId)) componentMap.set(rootId, []);
    componentMap.get(rootId).push(id);
  }

  const mergeGroups = [...componentMap.values()]
    .map((ids) => ids.sort((left, right) => order.get(left) - order.get(right)))
    .filter((ids) => ids.length > 1)
    .sort((left, right) => order.get(left[0]) - order.get(right[0]))
    .map((ids) => ({ keepId: ids[0], ids }));

  const summary = {
    generatedAt: new Date().toISOString(),
    sourceReports: reports.map((file) => path.relative(root, file).replace(/\\/g, "/")),
    decisions: groups.reduce((acc, group) => {
      acc[group.decision] = (acc[group.decision] || 0) + 1;
      return acc;
    }, {}),
    originalQuestionCount: questions.length,
    mergeGroupCount: mergeGroups.length,
    removedQuestionCount: mergeGroups.reduce((sum, group) => sum + group.ids.length - 1, 0),
    mergedQuestionCount: questions.length - mergeGroups.reduce((sum, group) => sum + group.ids.length - 1, 0),
    keptGroups: groups.filter((group) => group.decision === "keep"),
    missingIds: [...missing]
  };

  const data = `// Generated by scripts/build_merge_overrides.js from docs/duplicate_report.md and docs/similar_report.md.\n(function () {\n  const mergeGroups = ${JSON.stringify(mergeGroups, null, 2)};\n\n  function sourceKey(source) {\n    if (!source) return \"\";\n    return [source.sourceId || \"\", source.page || \"\", source.section || \"\", source.question || \"\"].join(\"|\");\n  }\n\n  function sourcesFor(question) {\n    if (!question) return [];\n    if (Array.isArray(question.sources) && question.sources.length) return question.sources;\n    return question.source ? [question.source] : [];\n  }\n\n  function hasPrioritySource(sources) {\n    return sources.some((source) => source && (source.sourceId === \"final\" || source.sourceId === \"af3\"));\n  }\n\n  const questions = window.QUESTION_BANK || [];\n  const byId = new Map(questions.map((question) => [question.id, question]));\n  const removeIds = new Set();\n\n  for (const group of mergeGroups) {\n    const groupQuestions = group.ids.map((id) => byId.get(id)).filter(Boolean);\n    if (groupQuestions.length < 2) continue;\n\n    const primary = byId.get(group.keepId) || groupQuestions[0];\n    const sources = [];\n    const seenSources = new Set();\n\n    for (const question of groupQuestions) {\n      for (const source of sourcesFor(question)) {\n        const key = sourceKey(source);\n        if (!key || seenSources.has(key)) continue;\n        sources.push({ ...source });\n        seenSources.add(key);\n      }\n    }\n\n    if (sources.length) {\n      primary.sources = sources;\n      primary.source = sources[0];\n    }\n    primary.finalExam = groupQuestions.some((question) => question.finalExam);\n    primary.reviewPriority = hasPrioritySource(sources);\n    primary.mergedQuestionIds = group.ids.slice();\n\n    for (const question of groupQuestions) {\n      if (question.id !== primary.id) removeIds.add(question.id);\n    }\n  }\n\n  window.QUESTION_MERGES = mergeGroups;\n  window.QUESTION_BANK = questions.filter((question) => !removeIds.has(question.id));\n})();\n`;

  const outFile = path.join(root, "data", "merge_overrides.js");
  const summaryFile = path.join(root, "data", "derived", "merge_summary.json");
  fs.writeFileSync(outFile, data, "utf8");
  fs.writeFileSync(summaryFile, `${JSON.stringify(summary, null, 2)}\n`, "utf8");
  console.log(outFile);
  console.log(summaryFile);
  console.log(JSON.stringify(summary, null, 2));
}

main();
