from __future__ import annotations

import json
from collections import Counter, defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DERIVED_DIR = ROOT / "data" / "derived"
DATA_DIR = ROOT / "data"
DOCS_DIR = ROOT / "docs"


def source_key(question: dict) -> tuple[str, str, str]:
    source = question["source"]
    return (source.get("sourceId", ""), source.get("section", ""), str(source.get("question", "")))


def load_json(path: Path) -> list[dict]:
    return json.loads(path.read_text(encoding="utf-8"))


def prepare_missing_question(question: dict) -> dict:
    next_question = dict(question)
    next_question["answerPending"] = True
    next_question["answer"] = None
    next_question["explanation"] = (
        "该题已从原 PDF 题号中补入，但当前 PDF 文本没有提供可机读标准答案；"
        "为避免编造答案，需按原 PDF 或课堂标准答案复核。"
    )
    next_question["finalExam"] = False
    if next_question["type"] in {"single_choice", "multiple_choice"} and "options" not in next_question:
        next_question["options"] = []
    return next_question


def write_js(missing: list[dict]) -> None:
    prepared = [prepare_missing_question(question) for question in missing]
    payload = json.dumps(prepared, ensure_ascii=False, indent=2)
    output = """// Generated by scripts/build_full_coverage_questions.py.
// These entries fill PDF question-number coverage gaps. Items marked answerPending
// are source-bound but intentionally not scored until their standard answers are verified.
(function () {
  const existing = new Set(
    window.QUESTION_BANK.map((question) => {
      const source = question.source || {};
      return `${source.sourceId || ""}|${source.section || ""}|${source.question || ""}`;
    })
  );
  const additions = __PAYLOAD__;
  additions.forEach((question) => {
    const source = question.source || {};
    const key = `${source.sourceId || ""}|${source.section || ""}|${source.question || ""}`;
    if (!existing.has(key)) {
      window.QUESTION_BANK.push(question);
      existing.add(key);
    }
  });
})();
""".replace("__PAYLOAD__", payload)
    (DATA_DIR / "full_coverage_questions.js").write_text(output, encoding="utf-8")


def write_report(extracted: list[dict], current: list[dict], missing: list[dict]) -> None:
    current_keys = {source_key(question) for question in current}
    summary: dict[str, Counter] = defaultdict(Counter)
    missing_summary: dict[str, Counter] = defaultdict(Counter)
    topic_summary = Counter()
    text_missing = []
    for question in extracted:
        source = question["source"]
        summary[source["sourceId"]][source["section"]] += 1
        if question.get("sourceTextMissing"):
            text_missing.append(question)
    for question in missing:
        source = question["source"]
        missing_summary[source["sourceId"]][source["section"]] += 1
        topic_summary[question["topic"]] += 1

    lines = [
        "# PDF Question Coverage Audit",
        "",
        "本报告由 `scripts/extract_pdf_questions.py` 与 `scripts/build_full_coverage_questions.py` 生成。",
        "审计对象为 4 个作业反馈 PDF：`assignment_feedback_1.pdf` 至 `assignment_feedback_4.pdf`。",
        "",
        f"- PDF 题号总数：{len(extracted)}",
        f"- 原网页题库题数：{len(current)}",
        f"- 原题库已覆盖 PDF 题号：{len(current_keys & {source_key(question) for question in extracted})}",
        f"- 本次补齐题号：{len(missing)}",
        "",
        "## PDF 原始题号统计",
        "",
        "| PDF | 题型板块 | 题号数 |",
        "|---|---:|---:|",
    ]
    for source_id in sorted(summary):
        for section, count in summary[source_id].items():
            lines.append(f"| {source_id} | {section} | {count} |")
    lines.extend(
        [
            "",
            "## 本次补齐题号统计",
            "",
            "| PDF | 题型板块 | 补齐数 |",
            "|---|---:|---:|",
        ]
    )
    for source_id in sorted(missing_summary):
        for section, count in missing_summary[source_id].items():
            lines.append(f"| {source_id} | {section} | {count} |")
    lines.extend(
        [
            "",
            "## 补齐题号按知识点分布",
            "",
            "| 知识点 | 补齐数 |",
            "|---|---:|",
        ]
    )
    for topic, count in topic_summary.most_common():
        lines.append(f"| {topic} | {count} |")
    lines.extend(["", "## 补齐题号明细", ""])
    by_source: dict[str, list[dict]] = defaultdict(list)
    for question in missing:
        by_source[question["source"]["sourceId"]].append(question)
    for source_id in sorted(by_source):
        lines.append(f"### {source_id}")
        for question in by_source[source_id]:
            source = question["source"]
            flag = "；PDF 文本缺失" if question.get("sourceTextMissing") else ""
            lines.append(
                f"- `{question['id']}`：{source['section']}第 {source['question']} 题，"
                f"知识点 `{question['topic']}`，p.{source['page']}{flag}"
            )
        lines.append("")
    lines.extend(["## PDF 文本提取为空但保留的题号", ""])
    if text_missing:
        for question in text_missing:
            source = question["source"]
            covered = "已在原题库中恢复" if source_key(question) in current_keys else "已补入待核对"
            lines.append(
                f"- `{question['id']}`：{source['sourceId']} {source['section']}第 {source['question']} 题，"
                f"p.{source['page']}，{covered}"
            )
    else:
        lines.append("- 无。")
    lines.append("")
    (DOCS_DIR / "question_coverage.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    extracted = load_json(DERIVED_DIR / "extracted_pdf_questions.json")
    current = load_json(DERIVED_DIR / "current_question_bank.json")
    current_keys = {source_key(question) for question in current}
    missing = [question for question in extracted if source_key(question) not in current_keys]
    write_js(missing)
    write_report(extracted, current, missing)


if __name__ == "__main__":
    main()
